import { IngredientItem } from '@/types/ingredient';

const RED = '#F28398';
const PINK = '#F8D4DC';
const BLUE = '#BEE6FF';
const GREEN = '#C8F2B4';
const YELLOW = '#FFE08A';
const CREAM = '#F6F0A8';
const SAND = '#E5CDAA';
const GRAY = '#E6E6E6';

export const INGREDIENT_LIBRARY: IngredientItem[] = [
  { id: 'chicken', name: 'Chicken', emoji: '🍗', bgColor: RED },
  { id: 'egg', name: 'Egg', emoji: '🥚', bgColor: SAND },
  { id: 'milk', name: 'Milk', emoji: '🥛', bgColor: BLUE },
  { id: 'bread', name: 'Bread', emoji: '🍞', bgColor: SAND },
  { id: 'cheese', name: 'Cheese', emoji: '🧀', bgColor: BLUE },
  { id: 'rice', name: 'Rice', emoji: '🍚', bgColor: GRAY },
  { id: 'pasta', name: 'Pasta', emoji: '🍝', bgColor: BLUE },
  { id: 'potato', name: 'Potato', emoji: '🥔', bgColor: YELLOW },
  { id: 'onion', name: 'Onion', emoji: '🧅', bgColor: PINK },
  { id: 'tomato', name: 'Tomato', emoji: '🍅', bgColor: YELLOW },
  { id: 'lettuce', name: 'Lettuce', emoji: '🥬', bgColor: GREEN },
  { id: 'ground-meat', name: 'Ground Meat', emoji: '🥩', bgColor: RED },
  { id: 'beef', name: 'Beef', emoji: '🥩', bgColor: RED },
  { id: 'bacon', name: 'Bacon', emoji: '🥓', bgColor: RED },
  { id: 'sausage', name: 'Sausage', emoji: '🌭', bgColor: RED },
  { id: 'carrot', name: 'Carrot', emoji: '🥕', bgColor: YELLOW },
  { id: 'apple', name: 'Apple', emoji: '🍎', bgColor: PINK },
  { id: 'banana', name: 'Banana', emoji: '🍌', bgColor: CREAM },
  { id: 'orange', name: 'Orange', emoji: '🍊', bgColor: YELLOW },
  { id: 'strawberry', name: 'Strawberry', emoji: '🍓', bgColor: RED },
  { id: 'blueberry', name: 'Blueberry', emoji: '🫐', bgColor: BLUE },
  { id: 'spinach', name: 'Spinach', emoji: '🥬', bgColor: GREEN },
  { id: 'cucumber', name: 'Cucumber', emoji: '🥒', bgColor: GREEN },
  { id: 'avocado', name: 'Avocado', emoji: '🥑', bgColor: GREEN },
  { id: 'sweet-potato', name: 'Sweet Potato', emoji: '🍠', bgColor: PINK },
  { id: 'corn', name: 'Corn', emoji: '🌽', bgColor: CREAM },
  { id: 'yogurt', name: 'Yogurt', emoji: '🥣', bgColor: BLUE },
  { id: 'salmon', name: 'Salmon', emoji: '🍣', bgColor: PINK },
  { id: 'turkey', name: 'Turkey', emoji: '🍗', bgColor: PINK },
  { id: 'ham', name: 'Ham', emoji: '🍖', bgColor: RED },
  { id: 'shrimp', name: 'Shrimp', emoji: '🦐', bgColor: PINK },
  { id: 'pork', name: 'Pork', emoji: '🥩', bgColor: RED },
  { id: 'tofu', name: 'Tofu', emoji: '⬜', bgColor: BLUE },
  { id: 'almond', name: 'Almond', emoji: '🫘', bgColor: GRAY },
  { id: 'cashew-nuts', name: 'Cashew Nuts', emoji: '🥜', bgColor: SAND },
  { id: 'mushroom', name: 'Mushroom', emoji: '🍄', bgColor: SAND },
  { id: 'green-bean', name: 'Green Bean', emoji: '🫛', bgColor: GREEN },
  { id: 'zucchini', name: 'Zucchini', emoji: '🥒', bgColor: GREEN },
  { id: 'grape', name: 'Grape', emoji: '🍇', bgColor: BLUE },
  { id: 'pear', name: 'Pear', emoji: '🍐', bgColor: CREAM },
  { id: 'peach', name: 'Peach', emoji: '🍑', bgColor: PINK },
  { id: 'mango', name: 'Mango', emoji: '🥭', bgColor: YELLOW },
  { id: 'lemon', name: 'Lemon', emoji: '🍋', bgColor: CREAM },
  { id: 'chia-seed', name: 'Chia Seed', emoji: '⚫', bgColor: SAND },
  { id: 'black-bean', name: 'Black Bean', emoji: '🫘', bgColor: SAND },
  { id: 'chickpea', name: 'Chickpea', emoji: '🫘', bgColor: GRAY },
  { id: 'kale', name: 'Kale', emoji: '🥬', bgColor: GREEN },
  { id: 'cauliflower', name: 'Cauliflower', emoji: '🥦', bgColor: GREEN },
  { id: 'bell-pepper', name: 'Bell Pepper', emoji: '🫑', bgColor: CREAM },
  { id: 'pumpkin', name: 'Pumpkin', emoji: '🎃', bgColor: YELLOW },
  { id: 'radish', name: 'Radish', emoji: '🌱', bgColor: PINK },
  { id: 'red-cabbage', name: 'Red Cabbage', emoji: '🥬', bgColor: PINK },
  { id: 'red-leaf-lettuce', name: 'Red Leaf Lettuce', emoji: '🥬', bgColor: PINK },
  { id: 'kiwi', name: 'Kiwi', emoji: '🥝', bgColor: GREEN },
  { id: 'artichoke', name: 'Artichoke', emoji: '🌿', bgColor: GREEN },
  { id: 'asparagus', name: 'Asparagus', emoji: '🥬', bgColor: GREEN },
  { id: 'crab-meat', name: 'Crab Meat', emoji: '🦀', bgColor: PINK },
  { id: 'clam', name: 'Clam', emoji: '🦪', bgColor: PINK },
  { id: 'cod', name: 'Cod', emoji: '🐟', bgColor: RED },
  { id: 'mussel', name: 'Mussel', emoji: '🦪', bgColor: PINK },
  { id: 'squid', name: 'Squid', emoji: '🦑', bgColor: PINK },
  { id: 'oyster', name: 'Oyster', emoji: '🦪', bgColor: PINK },
  { id: 'noodles', name: 'Noodles', emoji: '🍜', bgColor: SAND },
  { id: 'flour', name: 'Flour', emoji: '🥣', bgColor: GRAY },
  { id: 'water', name: 'Water', emoji: '🥛', bgColor: BLUE },
  { id: 'basil', name: 'Basil', emoji: '🌿', bgColor: GREEN },
  { id: 'cilantro', name: 'Cilantro', emoji: '🌿', bgColor: GREEN },
  { id: 'cherry', name: 'Cherry', emoji: '🍒', bgColor: RED },
  { id: 'honeydew-melon', name: 'Honeydew Melon', emoji: '🍈', bgColor: GREEN },
  { id: 'lamb-chop', name: 'Lamb Chop', emoji: '🍖', bgColor: RED },
  { id: 'bean-sprouts', name: 'Bean sprouts', emoji: '🌱', bgColor: PINK },
  { id: 'beef-bone', name: 'Beef bone', emoji: '🍖', bgColor: PINK },
  { id: 'beef-short-ribs', name: 'Beef short ribs', emoji: '🍖', bgColor: RED },
  { id: 'blood-sausage', name: 'Blood sausage', emoji: '🌭', bgColor: PINK },
  { id: 'chikuwa', name: 'Chikuwa', emoji: '🍢', bgColor: YELLOW },
  { id: 'deep-fried-tofu', name: 'Deep-fried tofu', emoji: '🧆', bgColor: SAND },
  { id: 'eel', name: 'Eel', emoji: '🐟', bgColor: PINK },
  { id: 'enoki-mushroom', name: 'Enoki mushroom', emoji: '🍄', bgColor: SAND },
  { id: 'fish-cake', name: 'Fish cake', emoji: '🍢', bgColor: CREAM },
  { id: 'fish-tofu', name: 'Fish tofu', emoji: '🧊', bgColor: CREAM },
  { id: 'gimbap-seaweed', name: 'Gimbap seaweed', emoji: '🍙', bgColor: GREEN },
  { id: 'glutinous-rice', name: 'Glutinous rice', emoji: '🍚', bgColor: CREAM },
  { id: 'instant-noodles', name: 'Instant noodles', emoji: '🍜', bgColor: BLUE },
  { id: 'kamaboko', name: 'Kamaboko', emoji: '🍥', bgColor: PINK },
  { id: 'king-oyster-mushroom', name: 'King oyster mushroom', emoji: '🍄', bgColor: SAND },
  { id: 'kombu', name: 'Kombu', emoji: '🌿', bgColor: GREEN },
  { id: 'matsutake-mushroom', name: 'Matsutake mushroom', emoji: '🍄', bgColor: SAND },
  { id: 'pacific-saury', name: 'Pacific saury', emoji: '🐟', bgColor: BLUE },
  { id: 'perilla-leaves', name: 'Perilla leaves', emoji: '🌿', bgColor: GREEN },
  { id: 'pork-belly', name: 'Pork belly', emoji: '🥓', bgColor: RED },
  { id: 'soju', name: 'Soju', emoji: '🍾', bgColor: BLUE },
  { id: 'tteok', name: 'Tteok', emoji: '🍡', bgColor: YELLOW },
  { id: 'udon-noodles', name: 'Udon noodles', emoji: '🍜', bgColor: BLUE },
  { id: 'water-dropwort', name: 'Water dropwort', emoji: '🌿', bgColor: GREEN },
  { id: 'yam', name: 'Yam', emoji: '🍠', bgColor: YELLOW },
  { id: 'abalone', name: 'Abalone', emoji: '🦪', bgColor: CREAM },
  { id: 'chestnut', name: 'Chestnut', emoji: '🌰', bgColor: CREAM },
  { id: 'chicken-gizzards', name: 'Chicken gizzards', emoji: '🫀', bgColor: PINK },
  { id: 'chives', name: 'Chives', emoji: '🌿', bgColor: GREEN },
  { id: 'dried-pollack', name: 'Dried pollack', emoji: '🐟', bgColor: YELLOW },
  { id: 'eggplant', name: 'Eggplant', emoji: '🍆', bgColor: BLUE },
  { id: 'fish-ball', name: 'Fish ball', emoji: '🍡', bgColor: SAND },
  { id: 'glass-noodles', name: 'Glass noodles', emoji: '🍜', bgColor: BLUE },
  { id: 'jujube', name: 'Jujube', emoji: '🫘', bgColor: PINK },
  { id: 'kimchi', name: 'Kimchi', emoji: '🥬', bgColor: PINK },
  { id: 'korean-beef', name: 'Korean beef', emoji: '🥩', bgColor: RED },
  { id: 'koya-dofu', name: 'Koya-dofu', emoji: '🧊', bgColor: CREAM },
  { id: 'natto', name: 'Natto', emoji: '🫘', bgColor: SAND },
  { id: 'scallops', name: 'Scallops', emoji: '🦪', bgColor: PINK },
  { id: 'seaweed', name: 'Seaweed', emoji: '🌿', bgColor: GREEN },
  { id: 'shirataki', name: 'Shirataki', emoji: '🍜', bgColor: CREAM },
  { id: 'short-neck-clams', name: 'Short-neck clams', emoji: '🦪', bgColor: PINK },
  { id: 'whitebait', name: 'Whitebait', emoji: '🐟', bgColor: YELLOW },
];

export const INGREDIENTS: IngredientItem[] = [
    { emoji: '🍕', name: 'bột bánh pizza', qty: '1 cái', bg: '#F5E6D3' },
    { emoji: '🧀', name: 'phô mai bào sợi', qty: '200 g', bg: '#D6EAF8' },
    { emoji: '🍅', name: 'sốt cà chua', qty: '100 ml', bg: '#FADBD8' },
    { emoji: '🫑', name: '1/2 quả ớt chuông thái nhỏ', qty: '...', bg: '#FEF9E7' },
  ];

const INGREDIENT_NAME_VI: Record<string, string> = {
  chicken: 'Gà',
  egg: 'Trứng',
  milk: 'Sữa',
  bread: 'Bánh mì',
  cheese: 'Phô mai',
  rice: 'Gạo',
  pasta: 'Pasta',
  potato: 'Khoai tây',
  onion: 'Hành tây',
  tomato: 'Cà chua',
  lettuce: 'Rau xà lách',
  'ground-meat': 'Thịt băm',
  beef: 'Thịt bò',
  bacon: 'Thịt xông khói',
  sausage: 'Xúc xích',
  carrot: 'Cà rốt',
  apple: 'Táo',
  banana: 'Chuối',
  orange: 'Cam',
  strawberry: 'Dâu tây',
  blueberry: 'Việt quất',
  spinach: 'Rau bina',
  cucumber: 'Dưa chuột',
  avocado: 'Bơ',
  'sweet-potato': 'Khoai lang',
  corn: 'Bắp',
  yogurt: 'Sữa chua',
  salmon: 'Cá hồi',
  turkey: 'Gà tây',
  ham: 'Giăm bông',
  shrimp: 'Tôm',
  pork: 'Thịt lợn',
  tofu: 'Đậu phụ',
  almond: 'Hạnh nhân',
  'cashew-nuts': 'Hạt điều',
  mushroom: 'Nấm',
  'green-bean': 'Đậu que',
  zucchini: 'Bí ngòi',
  grape: 'Nho',
  pear: 'Lê',
  peach: 'Đào',
  mango: 'Xoài',
  lemon: 'Chanh',
  'chia-seed': 'Hạt chia',
  'black-bean': 'Đậu đen',
  chickpea: 'Đậu gà',
  kale: 'Cải xoăn',
  cauliflower: 'Súp lơ trắng',
  'bell-pepper': 'Ớt chuông',
  pumpkin: 'Bí đỏ',
  radish: 'Củ cải đỏ',
  'red-cabbage': 'Bắp cải tím',
  'red-leaf-lettuce': 'Xà lách đỏ',
  kiwi: 'Kiwi',
  artichoke: 'Atiso',
  asparagus: 'Măng tây',
  'crab-meat': 'Thịt cua',
  clam: 'Nghêu',
  cod: 'Cá tuyết',
  mussel: 'Vẹm',
  squid: 'Mực',
  oyster: 'Hàu',
  noodles: 'Mì',
  flour: 'Bột mì',
  water: 'Nước',
  basil: 'Húng quế',
  cilantro: 'Rau mùi',
  cherry: 'Cherry',
  'honeydew-melon': 'Dưa lưới xanh',
  'lamb-chop': 'Sườn cừu',
  'bean-sprouts': 'Giá đỗ',
  'beef-bone': 'Xương bò',
  'beef-short-ribs': 'Sườn bò ngắn',
  'blood-sausage': 'Dồi huyết',
  chikuwa: 'Chikuwa',
  'deep-fried-tofu': 'Đậu phụ chiên',
  eel: 'Lươn',
  'enoki-mushroom': 'Nấm kim châm',
  'fish-cake': 'Chả cá',
  'fish-tofu': 'Đậu phụ cá',
  'gimbap-seaweed': 'Rong biển kimbap',
  'glutinous-rice': 'Gạo nếp',
  'instant-noodles': 'Mì ăn liền',
  kamaboko: 'Kamaboko',
  'king-oyster-mushroom': 'Nấm đùi gà',
  kombu: 'Rong biển kombu',
  'matsutake-mushroom': 'Nấm tùng nhung',
  'pacific-saury': 'Cá thu đao',
  'perilla-leaves': 'Lá tía tô',
  'pork-belly': 'Ba chỉ heo',
  soju: 'Soju',
  tteok: 'Bánh gạo',
  'udon-noodles': 'Mì udon',
  'water-dropwort': 'Rau cần nước',
  yam: 'Khoai từ',
  abalone: 'Bào ngư',
  chestnut: 'Hạt dẻ',
  'chicken-gizzards': 'Mề gà',
  chives: 'Hẹ',
  'dried-pollack': 'Cá minh thái khô',
  eggplant: 'Cà tím',
  'fish-ball': 'Viên cá',
  'glass-noodles': 'Miến',
  jujube: 'Táo tàu',
  kimchi: 'Kimchi',
  'korean-beef': 'Bò Hàn',
  'koya-dofu': 'Đậu phụ koya',
  natto: 'Natto',
  scallops: 'Sò điệp',
  seaweed: 'Rong biển',
  shirataki: 'Mì shirataki',
  'short-neck-clams': 'Nghêu cổ ngắn',
  whitebait: 'Cá cơm trắng',
};

const ingredientMap = new Map(INGREDIENT_LIBRARY.map((item) => [item.id, item]));

function isIngredientItem(item: IngredientItem | undefined): item is IngredientItem {
  return item !== undefined;
}

export function getIngredientById(id: string) {
  return ingredientMap.get(id);
}

export function getIngredientsByIds(ids: string[]) {
  return ids.map((id) => ingredientMap.get(id)).filter(isIngredientItem);
}

export function getIngredientDisplayName(ingredient: IngredientItem, locale: string) {
  if (locale.toLowerCase().startsWith('vi')) {
    return INGREDIENT_NAME_VI[ingredient.id] ?? ingredient.name;
  }

  return ingredient.name;
}

